export const conversations = [
  {
    id: "c1",
    name: "Meera Kapoor",
    role: "Customer · Order #4821",
    initials: "MK",
    online: true,
    unread: 2,
    lastAt: "2m",
    messages: [
      { id: "m1", from: "them", text: "Hi, is the Everyday Tote back in stock?", at: "10:02", status: "read" },
      { id: "m2", from: "me", text: "Yes! We just restocked it this morning.", at: "10:03", status: "read" },
      { id: "m3", from: "them", text: "Great, does it still ship in 2 days to Ludhiana?", at: "10:04", status: "read" },
      { id: "m4", from: "them", text: "Also do you have it in sand colour?", at: "10:04", status: "delivered" },
    ],
  },
  {
    id: "c2",
    name: "Rohan Bakshi",
    role: "Customer · Order #4790",
    initials: "RB",
    online: false,
    unread: 0,
    lastAt: "31m",
    messages: [
      { id: "m1", from: "them", text: "My payment failed twice on checkout.", at: "09:15", status: "read" },
      { id: "m2", from: "me", text: "Sorry about that — could you tell me the card's issuing bank?", at: "09:17", status: "read" },
      { id: "m3", from: "me", text: "I can also send a payment link via UPI instead.", at: "09:18", status: "read" },
      { id: "m4", from: "them", text: "UPI works, please send it.", at: "09:22", status: "read" },
    ],
  },
  {
    id: "c3",
    name: "Next Cart Support",
    role: "Internal · #escalations",
    initials: "NC",
    online: true,
    unread: 0,
    lastAt: "1h",
    messages: [
      { id: "m1", from: "them", text: "Webhook retries are stable after the ngrok fix.", at: "08:40", status: "read" },
      { id: "m2", from: "me", text: "Good, keeping an eye on UptimeRobot for the next hour.", at: "08:42", status: "read" },
    ],
  },
  {
    id: "c4",
    name: "Ishaan Verma",
    role: "Customer · Order #4756",
    initials: "IV",
    online: false,
    unread: 0,
    lastAt: "3h",
    messages: [
      { id: "m1", from: "them", text: "Thanks for the quick refund, appreciate it!", at: "06:05", status: "read" },
      { id: "m2", from: "me", text: "Anytime — let us know if anything else comes up.", at: "06:10", status: "read" },
    ],
  },
  {
    id: "c5",
    name: "Priya Nair",
    role: "Customer · Order #4803",
    initials: "PN",
    online: true,
    unread: 1,
    lastAt: "5h",
    messages: [
      { id: "m1", from: "them", text: "Can I change my delivery address?", at: "04:30", status: "delivered" },
    ],
  },
];